categories:  
  Lab Automation / High-Throughput:
    subcategories:
      Automated Liquid Handling Systems:
        subsubcategories:
          - Automated Workstations
          - Automated DNA/RNA/Protein Purification Systems
          - Specialized Liquid Handlers
          - Microplate Handlers

      Automated Workstations:
        subsubcategories:
          - Liquid Handling and Automated Workstations
          - Multipurpose Workstations
          - Automated DNA/RNA Extraction Systems
          - Protein Purification Workstations
          - Automated Cell Culture Systems

      Dispensing Systems:
        subsubcategories:
          - Aspiration Systems
          - Bottle-Top Dispensers
          - Microplate Dispensers
          - Microplate Washers
          - Pumps and Dispensing Equipment
